import autoLinkRule from "./inlines/autoLinkRule";
import codeSpanRule from "./inlines/codeSpanRule";
import commentSpanRule from "./inlines/commentSpanRule";
import emphasisRule from "./inlines/emphasisRule";
import hardBreakRule from "./inlines/hardBreakRule";
import highlightRule from "./inlines/highlightRule";
import inlineAttributesRule from "./inlines/inlineAttributesRule";
import linkRule from "./inlines/linkRule";
import rawSpanRule from "./inlines/rawSpanRule";
import spanRule from "./inlines/spanRule";
import strikethroughRule from "./inlines/strikethroughRule";
import superscriptRule from "./inlines/superscriptRule";
import textRule from "./inlines/textRule";
import type InlineRule from "./types/InlineRule";

let defaultInlineRules = new Map<string, InlineRule>();
defaultInlineRules.set(inlineAttributesRule.name, inlineAttributesRule);
defaultInlineRules.set(rawSpanRule.name, rawSpanRule);
defaultInlineRules.set(codeSpanRule.name, codeSpanRule);
defaultInlineRules.set(emphasisRule.name, emphasisRule);
defaultInlineRules.set(strikethroughRule.name, strikethroughRule);
defaultInlineRules.set(highlightRule.name, highlightRule);
defaultInlineRules.set(superscriptRule.name, superscriptRule);
defaultInlineRules.set(linkRule.name, linkRule);
defaultInlineRules.set(autoLinkRule.name, autoLinkRule);
defaultInlineRules.set(spanRule.name, spanRule);
defaultInlineRules.set(hardBreakRule.name, hardBreakRule);
defaultInlineRules.set(commentSpanRule.name, commentSpanRule);
defaultInlineRules.set(textRule.name, textRule);
export default defaultInlineRules;
