import asideRule from "./blocks/asideRule";
import blockAttributesRule from "./blocks/blockAttributesRule";
import blockQuoteRule from "./blocks/blockQuoteRule";
import codeBlockRule from "./blocks/codeBlockRule";
import commentRule from "./blocks/commentRule";
import displayRule from "./blocks/detailsRule";
import divRule from "./blocks/divRule";
import footnoteReferenceRule from "./blocks/footnoteReferenceRule";
import headingRule from "./blocks/headingRule";
import headingUnderlineRule from "./blocks/headingUnderlineRule";
import linkReferenceRule from "./blocks/linkReferenceRule";
import listBulletedRule from "./blocks/listBulletedRule";
import listOrderedRule from "./blocks/listOrderedRule";
import paragraphRule from "./blocks/paragraphRule";
import rawBlockRule from "./blocks/rawBlockRule";
import sectionBreakRule from "./blocks/sectionBreakRule";
import tableRule from "./blocks/tableRule";
import taskItemRule from "./blocks/taskItemRule";
import type BlockRule from "./types/BlockRule";

let defaultBlockRules = new Map<string, BlockRule>();
defaultBlockRules.set(blockAttributesRule.name, blockAttributesRule);
defaultBlockRules.set(headingRule.name, headingRule);
defaultBlockRules.set(headingUnderlineRule.name, headingUnderlineRule);
defaultBlockRules.set(sectionBreakRule.name, sectionBreakRule);
defaultBlockRules.set(listBulletedRule.name, listBulletedRule);
defaultBlockRules.set(listOrderedRule.name, listOrderedRule);
defaultBlockRules.set(taskItemRule.name, taskItemRule);
defaultBlockRules.set(blockQuoteRule.name, blockQuoteRule);
defaultBlockRules.set(displayRule.name, displayRule);
defaultBlockRules.set(asideRule.name, asideRule);
defaultBlockRules.set(codeBlockRule.name, codeBlockRule);
defaultBlockRules.set(rawBlockRule.name, rawBlockRule);
defaultBlockRules.set(tableRule.name, tableRule);
defaultBlockRules.set(divRule.name, divRule);
defaultBlockRules.set(footnoteReferenceRule.name, footnoteReferenceRule);
defaultBlockRules.set(linkReferenceRule.name, linkReferenceRule);
defaultBlockRules.set(commentRule.name, commentRule);
defaultBlockRules.set(paragraphRule.name, paragraphRule);
export default defaultBlockRules;
